### ISSUE TITLE
Suggested text items in the preview bar not working

### ISSUE THREAD

**Issue by kasti0** [CreatureSurvive/Fabric#1]
I‘m using an iPhone X, 12.1.2 on u0. When I type your suggested text items e.g. for 24hr format or the battery status they just don’t work or display weird values on the lockscreen. I‘m using my iPhone in German, maybe it has to do with that.

**Comment by ahanank** [comment]
Same here

**Comment by CreatureSurvive** [comment]
Would you mind including a screenshot of both the format string in the settings, and the result it produces on the lockscreen? This will help me get a better understanding of the issue and help in fixing it.

**Comment by ahanank** [comment]
https://i.imgur.com/NbyHxRy.jpg
https://i.imgur.com/kZArNEq.png

This is just one example, other times a string won’t even show up and ‘ inverted commas’ show up instead

**Comment by CreatureSurvive** [comment]
Alright thanks for providing that, I think I see the issue, it looks like it's placing `’` in the format string instead of `'` and that's causing issues. I think this as a language specific issue and I will look into fixing this.

**Comment by ahanank** [comment]
Awesome, glad that helped. Keep making great tweaks! Hope Consolidation makes a grand comeback someday :))

**Comment by kasti0** [comment]
I can confirm that placing ' manually fixes the problem with battery status and battery level. For the 24hr format it should be „HH“ (without „“) but your suggested text sting inserts „EEEE“ (without „“) which is the code for weekday.

**Comment by CreatureSurvive** [comment]
Thanks for the details on this @kasti0, it looks like there is some automatic conversion going on for `'` in some languages which makes my parser ignore them. It should be an easy fix, though I'm not sure of the exact character it's being replaced with since there are multiple variations of the character `', ‘, ’` so I may just need to check for all of them. As for the `HH` vs `EEEE` that was just a careless mistake on my part and I'll resolve that right now.

**Comment by CreatureSurvive** [comment]
I believe I have this issue fixed now, the solution will be included in the next release.
